name: build-deploy
on: [push]

permissions:
      id-token: write
      contents: read

jobs:
  Windows-latest:
      runs-on: windows-latest
      steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build . -t ${{ secrets.REGISTRY_SERVER }}/remixazuredocker:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_SERVER }}/remixazuredocker:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'remix-web-app-for-containers'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ secrets.REGISTRY_SERVER }}/remixazuredocker:${{ github.sha }}'

      - name: Azure logout
        run: |
          az logout